databases:
  - name: cellstore-db
    plan: free
    databaseName: cellstore_db
    user: cellstore

services:
  - type: web
    name: cellstore-api
    plan: free
    runtime: node
    buildCommand: npm install && cd packages/server && npm install --save-dev @types/node @types/express @types/cors @types/morgan && npx prisma generate && cd ../shared && npx tsc && cd ../server && npx tsc
    startCommand: cd packages/server && npx prisma migrate deploy && node dist/server.js
    rootDir: .
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cellstore-db
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3333"
      - key: CORS_ORIGIN
        value: https://cellstore-delta.vercel.app
    healthCheckPath: /api/v1/health